name: Build sveltekit project as static page in build/
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install
      - run: npm run build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./build
